import type { ConfigContext, ExpoConfig } from 'expo/config';

/**
 * Expo app configuration.
 *
 * This is a TypeScript config (not app.json) so that build-time values can be
 * derived from the environment. Anything read here runs on the *build machine*,
 * never on the device.
 *
 * Note the split in how environment variables are used:
 *   - `EXPO_PUBLIC_*` values consumed by app code are validated at runtime by
 *     src/config/env.ts.
 *   - Values needed to configure *native* projects (Google Maps API keys, for
 *     example) must be injected here, because native config is generated at
 *     build time and cannot read a runtime value.
 */

const APP_NAME = 'Accident Black Spot Detection';
const APP_SLUG = 'accident-black-spot-detection';
const APP_SCHEME = 'accidentblackspotdetection';
const BUNDLE_ID = 'com.shreyuu.accidentblackspotdetection';

/**
 * The user-facing version. Semantic; bumped by hand, in a commit of its own.
 *
 * Deliberately **not** derived from package.json. The npm version of a private
 * workspace is metadata nobody reads; this string appears in App Store Connect,
 * in Play Console, and in Settings, and changing it is a release decision rather
 * than a side effect of a dependency bump. Phase 14 keeps them numerically equal
 * (both 0.1.0) but not linked — see docs/builds-and-releases.md.
 */
const APP_VERSION = '0.1.0';

/**
 * The build number, shared by `ios.buildNumber` and `android.versionCode`.
 *
 * One number for both platforms, because the alternative — two counters drifting
 * apart — makes "which build is this crash from?" unanswerable without a lookup
 * table. Both stores only require that it increase; neither requires the two to
 * be independent.
 *
 * ## Why this is a committed constant and not `autoIncrement`
 *
 * `eas.json` originally set `autoIncrement: true` on the production profile with
 * `appVersionSource: "local"`. That combination **cannot work here**: local
 * auto-increment means EAS CLI rewrites the version in the app config, and this
 * project's config is `app.config.ts` — dynamic, generated by running code, so
 * there is nothing for the CLI to write back into. The flag was inert at best.
 *
 * The two working alternatives were:
 *
 *   - `appVersionSource: "remote"`, letting EAS hold the counter server-side.
 *     Works with a dynamic config, but makes the build number a property of an
 *     EAS account rather than of the commit, and this project has no EAS project
 *     linked yet (there is no `extra.eas.projectId`).
 *   - This: a number in the repository, bumped in the release commit.
 *
 * The second was chosen because it keeps the build number reproducible from a
 * checkout alone. `git show <tag>:apps/mobile/app.config.ts` answers what any
 * shipped build number was, offline, with no account.
 *
 * `APP_BUILD_NUMBER` overrides it so CI can substitute a monotonic run number
 * for internal distribution without a commit. It is validated rather than
 * trusted: a malformed value here produces a build the store rejects at upload,
 * long after it is convenient to find out.
 */
function resolveBuildNumber(): number {
  const FALLBACK = 1;

  const raw = process.env.APP_BUILD_NUMBER?.trim();
  if (raw === undefined || raw.length === 0) {
    return FALLBACK;
  }

  const parsed = Number(raw);
  if (!Number.isInteger(parsed) || parsed < 1) {
    throw new Error(
      `APP_BUILD_NUMBER must be a positive integer, got ${JSON.stringify(raw)}. ` +
        'Both stores reject a non-integer build number at upload, so this fails here instead.',
    );
  }

  return parsed;
}

type AppVariant = 'development' | 'preview' | 'production';

function resolveVariant(): AppVariant {
  const raw = process.env.EXPO_PUBLIC_APP_ENV;
  if (raw === 'preview' || raw === 'production') {
    return raw;
  }
  return 'development';
}

/**
 * Separate identifiers per variant so a development build, a preview build and
 * a store build can all be installed on the same device simultaneously.
 */
function identifierFor(variant: AppVariant): string {
  switch (variant) {
    case 'development':
      return `${BUNDLE_ID}.dev`;
    case 'preview':
      return `${BUNDLE_ID}.preview`;
    case 'production':
      return BUNDLE_ID;
  }
}

function displayNameFor(variant: AppVariant): string {
  switch (variant) {
    case 'development':
      return `${APP_NAME} (Dev)`;
    case 'preview':
      return `${APP_NAME} (Preview)`;
    case 'production':
      return APP_NAME;
  }
}

/** Trims a build-machine env var to `undefined` when unset or blank. */
function optionalEnv(value: string | undefined): string | undefined {
  const trimmed = value?.trim();
  return trimmed === undefined || trimmed.length === 0 ? undefined : trimmed;
}

export default ({ config }: ConfigContext): ExpoConfig => {
  const variant = resolveVariant();
  const identifier = identifierFor(variant);
  const buildNumber = resolveBuildNumber();

  // Read here rather than in src/config/env.ts because native map configuration
  // is generated at build time and cannot consult a runtime value.
  const googleMapsKeyAndroid = optionalEnv(process.env.EXPO_PUBLIC_GOOGLE_MAPS_API_KEY_ANDROID);
  const googleMapsKeyIos = optionalEnv(process.env.EXPO_PUBLIC_GOOGLE_MAPS_API_KEY_IOS);

  return {
    ...config,
    name: displayNameFor(variant),
    slug: APP_SLUG,
    version: APP_VERSION,
    orientation: 'portrait',
    scheme: APP_SCHEME,
    // "automatic" lets the OS light/dark setting drive the app theme. The
    // design system honours this; see src/theme/ThemeProvider.tsx.
    userInterfaceStyle: 'automatic',
    icon: './assets/images/icon.png',

    ios: {
      bundleIdentifier: identifier,
      buildNumber: String(buildNumber),
      supportsTablet: true,
      config: {
        // Only needed for provider={PROVIDER_GOOGLE}. iOS uses Apple Maps by
        // default, which needs no key — see the note on the plugins array below.
        ...(googleMapsKeyIos === undefined ? {} : { googleMapsApiKey: googleMapsKeyIos }),
      },
      infoPlist: {
        // The expo-location plugin writes this deprecated iOS 10-era key with its
        // generic default and offers no option to set it. It is inert at our
        // deployment target, but a placeholder purpose string should not ship in
        // a binary, so it is overridden here to match the other two.
        NSLocationAlwaysUsageDescription:
          'Accident Black Spot Detection can warn you about nearby accident-prone areas while the app is in the background. This is optional and off by default.',
        // UIBackgroundModes is NOT set here. The expo-location plugin appends
        // "location" to it, and expo-task-manager's own plugin appends "fetch"
        // unconditionally — both run after this object is applied, so anything
        // written here is added to rather than replaced.
        //
        // Phase 14 removes the unused "fetch" entry with the local
        // `withoutUnusedBackgroundModes` plugin, listed last in `plugins` below
        // because only a mod registered after those two can subtract from what
        // they added.
      },
    },

    android: {
      package: identifier,
      versionCode: buildNumber,
      adaptiveIcon: {
        foregroundImage: './assets/images/android-icon-foreground.png',
        backgroundImage: './assets/images/android-icon-background.png',
        monochromeImage: './assets/images/android-icon-monochrome.png',
        backgroundColor: '#0B1F3A',
      },
      // Note: there is no `edgeToEdgeEnabled` flag in SDK 57 — edge-to-edge is
      // unconditional on Android now, which is why every screen must go through
      // ScreenContainer for safe-area insets rather than assuming an inset-free
      // viewport.
      predictiveBackGestureEnabled: false,
      config: {
        // Android has no non-Google map provider, so a development or release
        // build needs its own key or the map renders as a blank grid. Expo Go
        // supplies its own key, which is why the map works there without this.
        ...(googleMapsKeyAndroid === undefined
          ? {}
          : { googleMaps: { apiKey: googleMapsKeyAndroid } }),
      },
      // Every location permission — ACCESS_COARSE_LOCATION, ACCESS_FINE_LOCATION,
      // ACCESS_BACKGROUND_LOCATION, FOREGROUND_SERVICE and
      // FOREGROUND_SERVICE_LOCATION — is contributed by the expo-location plugin
      // below. Listing any of them here as well produced duplicate entries in the
      // merged manifest.
      //
      // SYSTEM_ALERT_WINDOW is written into the main manifest by Expo's prebuild
      // template, not by anything here, and is removed again by
      // `withoutUnusedCapabilities`. The template's separate debug-only
      // declaration is left alone, so React Native's dev overlay is unaffected.
    },

    web: {
      output: 'static',
      favicon: './assets/images/favicon.png',
    },

    plugins: [
      // MUST BE FIRST, which is the opposite of what it looks like.
      //
      // Expo's mods run in REVERSE registration order: `withMod` wraps the
      // previously-registered mod, and each action runs before chaining down to
      // it, so the earliest-listed plugin's action is the last one to touch
      // modResults before the base mod writes the file. Autolinked plugins —
      // expo-task-manager among them — are registered after everything listed
      // here, which means they run first of all.
      //
      // This plugin only subtracts, so it has to see every addition. Listed last
      // it ran before expo-location had contributed "location", found only the
      // "fetch" that autolinked expo-task-manager had just added, and failed its
      // own assertion. That failure is the reason the assertion exists.
      './plugins/withoutUnusedCapabilities',
      'expo-router',
      // Required so the Keychain/Keystore entitlements are configured. The auth
      // session is persisted here rather than in AsyncStorage because it contains
      // a refresh token — see src/services/firebase/secureAuthStorage.ts.
      'expo-secure-store',
      [
        'expo-location',
        {
          // These strings are what the user actually reads in the OS permission
          // dialog, so they name the feature rather than saying "for a better
          // experience". The in-app PermissionCard shown beforehand carries the
          // fuller explanation, including what is not stored.
          locationWhenInUsePermission:
            'Accident Black Spot Detection uses your location to warn you when you approach a known accident-prone or crime-prone area.',
          // Read by the OS when the app asks to upgrade to "Always" — which only
          // happens after the user has switched background monitoring on and
          // read the in-app disclosure. The generic default the plugin would
          // otherwise write ("Allow $(PRODUCT_NAME) to access your location") is
          // both an App Store review rejection and, more importantly, not enough
          // for the user to make an informed choice.
          locationAlwaysAndWhenInUsePermission:
            'Accident Black Spot Detection can warn you about nearby accident-prone areas while the app is in the background. This is optional and off by default.',
          // Phase 8. These three flags are what make background monitoring
          // possible at all, and each one has a user-visible cost:
          //
          //   - iOS gains the `location` background mode, and with it the blue
          //     status-bar indicator whenever the task is running.
          //   - Android gains ACCESS_BACKGROUND_LOCATION, which Android 11+
          //     presents as a separate "Allow all the time" trip to Settings.
          //   - The foreground service is what stops Android killing the task
          //     within minutes; it is legally and practically required to show a
          //     persistent notification while it runs.
          //
          // None of this activates on its own: the permissions merely exist in
          // the binary. `backgroundMonitoringEnabled` defaults to false, the
          // disclosure in Settings is shown before anything is requested, and
          // nothing is started until the user opts in. See
          // docs/background-monitoring.md.
          isIosBackgroundLocationEnabled: true,
          isAndroidBackgroundLocationEnabled: true,
          isAndroidForegroundServiceEnabled: true,
          // Resized by the plugin to a 24dp baseline across every density and
          // written to res/drawable. Android renders it from its alpha channel
          // alone; see the note in the source SVG for why this asset is the
          // warning triangle rather than the app's pin.
          androidForegroundServiceIcon: './assets/images/notification-icon.png',
        },
      ],
      [
        // Phase 4 delivers proximity alerts through expo-notifications, but the
        // package was used without its config plugin until now — so Android drew
        // the launcher icon, downsampled to 24dp and reduced to a white blob,
        // in the status bar. The plugin is what makes a dedicated silhouette
        // possible. iOS ignores both options: it uses the app icon and does not
        // tint notification icons.
        'expo-notifications',
        {
          icon: './assets/images/notification-icon.png',
          // The tint Android applies to the silhouette and to the app name on
          // the notification. `amber300`, matching the mark — chosen over
          // `danger` red deliberately: every proximity alert would otherwise
          // arrive looking like the most severe one.
          color: '#F0B449',
        },
      ],
      [
        'expo-image-picker',
        {
          // Shown in the OS dialogs when a reporter attaches a photograph. Both
          // name the feature rather than saying "to improve your experience" —
          // a vague purpose string is both a review rejection and a reason for
          // the user to refuse.
          photosPermission:
            'Accident Black Spot Detection needs access to your photos so you can attach one to an incident report. Photos are only uploaded with a report you submit.',
          cameraPermission:
            'Accident Black Spot Detection needs access to your camera so you can photograph an incident you are reporting. Photos are only uploaded with a report you submit.',
          // The app never saves to the library, so the write-only permission is
          // not requested at all.
          microphonePermission: false,
        },
      ],
      // Contributes the Android manifest bits the date/time dialogs need. The
      // package has no configurable options.
      '@react-native-community/datetimepicker',
      [
        'expo-splash-screen',
        {
          backgroundColor: '#0B1F3A',
          image: './assets/images/splash-icon.png',
          imageWidth: 180,
          dark: {
            backgroundColor: '#060F1D',
            image: './assets/images/splash-icon.png',
            imageWidth: 180,
          },
        },
      ],
    ],

    experiments: {
      typedRoutes: true,
      reactCompiler: true,
    },

    extra: {
      // Surfaced to app code through expo-constants. Useful for showing the
      // active variant in Settings and in bug reports.
      appVariant: variant,
    },
  };
};
