/**
 * Is generated native build output tracked in the repository?
 *
 * `.gitignore` already says it must not be — "Generated by `expo prebuild` —
 * regenerate, never commit". But a `.gitignore` rule only prevents what it is
 * anchored to, and in Phase 14 that anchoring was the whole problem: the rules
 * named `/apps/mobile/ios/`, somebody ran `expo prebuild` from the repository
 * root instead, and commit cbd8a2d tracked 13 files of a second Xcode project
 * at `/ios` that nothing referenced.
 *
 * Nothing objected. `.prettierignore` is scoped to `apps/mobile/ios/` for the
 * same reason the `.gitignore` rule was, ESLint runs per workspace and the root
 * is not one, and the secret scanner found no secrets because there were none.
 * Thirteen files entered the repository with no gate holding an opinion about
 * whether they belonged.
 *
 * So this is the gate that holds the opinion. It is a *tracked-path* check
 * rather than another ignore rule on purpose: an ignore rule that is wrong is
 * silent, and silence is what let this through. A failing check names the file
 * and says what to do about it.
 *
 * Detection lives here, separate from the script that runs it, so it can be
 * unit-tested against fixture lists rather than only against the repository's
 * real files — the same split as `workflowParity.mjs`.
 */

/**
 * Paths that must never be tracked, and the reason each one is forbidden.
 *
 * A prefix ending in `/` matches a directory and everything beneath it; one
 * without matches that exact path. The reason is carried alongside the pattern
 * because a failure message that only says "this is forbidden" sends the reader
 * back to the commit log to find out why.
 *
 * @type {ReadonlyArray<{ prefix: string, reason: string }>}
 */
export const FORBIDDEN = Object.freeze([
  {
    prefix: 'ios/',
    reason:
      'an `expo prebuild` run from the repository root; the app lives in apps/mobile and generates apps/mobile/ios/',
  },
  {
    prefix: 'android/',
    reason:
      'an `expo prebuild` run from the repository root; the app lives in apps/mobile and generates apps/mobile/android/',
  },
  {
    prefix: 'app.json',
    reason:
      'a second Expo config competing with apps/mobile/app.config.ts, which is the one the build reads',
  },
  {
    prefix: 'apps/mobile/ios/',
    reason: 'generated by `expo prebuild`; regenerate it rather than tracking it',
  },
  {
    prefix: 'apps/mobile/android/',
    reason: 'generated by `expo prebuild`; regenerate it rather than tracking it',
  },
  {
    prefix: 'functions/lib/',
    reason: 'the `tsc` emit for the functions workspace; `npm run functions:build` regenerates it',
  },
]);

/**
 * Finds tracked paths that are generated native build output.
 *
 * @param {readonly string[]} trackedFiles Repository-relative paths, as
 *   `git ls-files` prints them (forward slashes, no leading `./`).
 * @param {ReadonlyArray<{ prefix: string, reason: string }>} [forbidden]
 *   Overridable for tests; defaults to {@link FORBIDDEN}.
 * @returns {Array<{ path: string, reason: string }>} One entry per offending
 *   file, in the order they were supplied.
 */
export function offendingPaths(trackedFiles, forbidden = FORBIDDEN) {
  const offenders = [];

  for (const path of trackedFiles) {
    for (const { prefix, reason } of forbidden) {
      const matches = prefix.endsWith('/') ? path.startsWith(prefix) : path === prefix;
      if (matches) {
        offenders.push({ path, reason });
        break;
      }
    }
  }

  return offenders;
}

/**
 * Renders offenders as a message a reader can act on without further digging.
 *
 * Groups by rule rather than listing 13 sibling files with the same
 * explanation repeated after each one.
 *
 * @param {ReadonlyArray<{ path: string, reason: string }>} offenders
 * @returns {string} Empty string when there are none.
 */
export function formatOffenders(offenders) {
  if (offenders.length === 0) return '';

  /** @type {Map<string, string[]>} */
  const byReason = new Map();
  for (const { path, reason } of offenders) {
    const paths = byReason.get(reason) ?? [];
    paths.push(path);
    byReason.set(reason, paths);
  }

  const sections = [];
  for (const [reason, paths] of byReason) {
    const shown = paths.slice(0, 5);
    const remainder = paths.length - shown.length;
    const list = shown.map((path) => `    ${path}`).join('\n');
    const more = remainder > 0 ? `\n    …and ${remainder} more` : '';
    sections.push(`  ${reason}\n${list}${more}`);
  }

  return [
    `Generated native build output is tracked (${offenders.length} file(s)):`,
    '',
    sections.join('\n\n'),
    '',
    'Untrack it, then commit the removal:',
    '',
    '    git rm -r --cached <path>',
    '',
  ].join('\n');
}
